annealing:
  - class: File
    path: ../../SimulatedAnnealing/Makefile
  - class: Directory
    path: ../../SimulatedAnnealing/src
clustering:
  - class: File
    path: ../../Makefile
  - class: File
    path: ../../clustering.cpp
  - class: File
    path: ../../common.cpp
  - class: File
    path: ../../silhouette.cpp
  - class: Directory
    path: ../../include
  - class: Directory
    path: ../../vendor
points:
  class: File
  path: ../../data/input/cluster_points_80k.csv
threshold: 0.8
